version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/crop.db:/app/crop.db
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8001
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
